### ISSUE TITLE
Bug: Renders canvas elements visible on the page

### ISSUE THREAD

**Issue by danpalmer** [akfish/node-vibrant#36]
While we could solve this with the addition of some CSS, it's a little tricky to target the canvas elements created by node-vibrant as they have no class and are not contained within another element, meaning that we must have a very general CSS rule to hide them, which is not ideal.

**Comment by akfish** [comment]
Noted. Will fix in next version.
- [ ] Hiding `<canvas>` element with inline style
- [ ] (Optional) Custom `<canvas>` class name

**Comment by akfish** [comment]
Fixed in v3.0.0-alpha.1

Changes made to `<canvas>` element:
* Added `visibility: hidden` as inline style
* Added class name `vibrant-canvas`

**Comment by SalGnt** [comment]
I still face this problem, even using the latest version.  The problem is that `visibility: hidden` allocate the space of the canvas on the page. I suggest to swap `visibility: hidden` with `display: none` if possible.

**Comment by SalGnt** [comment]
I still face this problem, even using the latest version. The problem is that visibility: hidden allocate the space of the canvas on the page. My suggestion is to swap visibility: hidden with display: none if possible.

**Comment by SalGnt** [comment]
I still face this problem, even using the latest version. The problem is that with `visibility: hidden` the space of the canvas is allocated on the page. My suggestion is to swap `visibility: hidden` with `display: none`.
